### PR TITLE
Accurately reflect Skynet-File-Metadata JSON

### PR DESCRIPTION
**Pull request by drmathias**

### CODE REVIEW

**Review by m-cat — CHANGES_REQUESTED** [review]
Thanks, I copied this over from the Sia API docs -- I'll fix it there as well.

Please also read the "Contributing" section of the README -- specifically, these changes should be copied to `source/includes/_downloading.md `.

**Review by m-cat — CHANGES_REQUESTED** [review]
Also, mind re-indenting these blocks and documenting the filename key as `// string`? e.g.:

```javascript
{
  "mode":     640,      // os.FileMode
  "filename": "folder", // string
  "subfiles": {         // []SkyfileSubfileMetadata | null
    "folder/file1.txt": {                 // string
      "mode":         640,                // os.FileMode
      "filename":     "folder/file1.txt", // string
      "contenttype":  "text/plain",       // string
      "offset":       0,                  // uint64
      "len":          6                   // uint64
    }
  }
}
```

**Comment by drmathias** [comment]
Do you want the data type comments on all of the different SDK examples? Sorry, I'm on Windows and the git-hook doesn't work as expected as files get copied to /v2/includes/includes so manually updated across each version.

**Review by m-cat — APPROVED** [review]
Thanks!

> Do you want the data type comments on all of the different SDK examples? 

Nah, I don't think it's necessary actually.

> Sorry, I'm on Windows and the git-hook doesn't work as expected as files get copied to /v2/includes/includes

Well that's annoying 😅

**Pull request merged**
